# Numpy Excercises

In [1]:
import numpy as np

## 1- Basics

- A- Create a 1D array of 10 evenly spaced values between 5 and 50
- B- Redo it with excluding the endpoint
- Compare between the distance of the values in both cases

In [4]:
arr = np.linspace(5, 50, 10)
arr_no_endpoint = np.linspace(5, 50, 10, endpoint=False)
print(arr)
print(arr_no_endpoint)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[ 5.   9.5 14.  18.5 23.  27.5 32.  36.5 41.  45.5]


- Create a 3×3 NumPy array of all True (can you do this in one line of code without using True/False values?).

In [ ]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- Create a 1D array of 10 random integers between 190 and 200 (inclusive).

In [24]:
np.random.randint(190, 201, size=10)


array([194, 198, 198, 197, 200, 192, 193, 190, 197, 195])

## 2- Slicing

- Reverse a 1D NumPy array

In [7]:
arr = np.arange(10)

In [ ]:
arr = np.arange(10)
reversed_arr = arr[::-1]
reversed_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

- Reverse each row in a matrix

In [32]:
arr1 = np.arange(10).reshape((2, 5))
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr1 = np.arange(10).reshape((2, 5))
arr1[:, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

- Create a 4×4 array and extract its first row and last column

In [10]:
arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr, "\n")

first_row = arr[0]
print(first_row)

last_col = arr[:, -1]
print(last_col)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[1 2 3 4]
[ 4  8 12 16]


- Select elements at positions 0th, 2nd, 5th from the array:

In [ ]:
arr = np.array([5,10,15,20,25,30])


In [ ]:
arr[[0,2,5]]


array([ 5, 15, 30])

From the following array,  
- Slice the first two rows and first two columns from a 4×4 array
- Extract Odd Rows and Even Columns
- Replace all odd numbers in a NumPy array with -1

In [13]:
arr = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])

In [14]:
arr[0:2, 0:2]

array([[ 3,  6],
       [15, 18]])

In [15]:
arr[1::2, ::2]


array([[15, 21],
       [39, 45]])

In [16]:
arr[arr % 2 == 1] = -1
arr

array([[-1,  6, -1, 12],
       [-1, 18, -1, 24],
       [-1, 30, -1, 36],
       [-1, 42, -1, 48],
       [-1, 54, -1, 60]])

- select all even negative numbers.

In [34]:
arr = np.arange(-10, 11)


In [37]:
arr[(arr < 0) & (arr % 2 == 0)]

array([-10,  -8,  -6,  -4,  -2])

- Replace all values between 10 and 20 (inclusive) with 0.

In [29]:
np.random.seed(42)

arr = np.random.randint(30, size = 100)

In [28]:
np.random.seed(42)

arr = np.random.randint(30, size = 100)
arr[(arr >= 10) & (arr <= 20)] = 0
arr

array([ 6,  0, 28,  0,  0,  7, 28,  0,  6, 25,  0, 22,  0,  0, 23,  0,  3,
        7, 23,  2, 21,  0,  1, 23,  0, 29,  5,  1, 27,  0,  0,  0, 25, 21,
       28,  0, 24,  0, 26, 26,  9, 27, 27,  0,  0, 29, 29,  0, 29,  0,  0,
       22,  0, 24,  2,  4,  0,  6,  0,  8,  6,  0,  3, 24, 27,  0,  0, 25,
        8, 25,  0,  1,  0, 27,  0, 27,  6,  0, 28,  7,  0,  2,  0,  0,  3,
        0,  7,  3,  1, 29,  5, 21,  9,  3, 21, 28,  0, 25,  0,  1])

- Swap row 0 and row 2 of a 3×3 array using one line.

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[0], arr[2] = arr[2].copy(), arr[0].copy()
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 3- Manipulation

Find the common items between two arrays
- Solve it twice one with np.intersect1d
- and another using np.isin with np.unique


Then find the elements that are in array a but not in b.

In [15]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

In [21]:
mask = np.isin(a, b)
np.unique(a[mask])

array([2, 4, 8])

In [ ]:
np.intersect1d(a, b)

array([2, 4, 8])

In [22]:
mask = ~ np.isin(a, b)
np.unique(a[mask])

array([1, 3])

- Remove all occurances of the number 5 from an array

In [ ]:
arr = np.array([3, 5, 2, 5, 1, 5, 7])

In [3]:
arr = np.array([3, 5, 2, 5, 1, 5, 7])
res = arr[arr != 5]
res

array([3, 2, 1, 7])

- Find all elements greater than the mean

In [7]:
arr = np.array([2, 6, 1, 9, 3, 8])


In [6]:
arr = np.array([2, 6, 1, 9, 3, 8])
res = arr[arr > arr.mean()]
res


array([6, 9, 8])

Find the row with the maximum sum in a 2D array.
- Hint: check np.argmax

In [36]:
np.random.seed(42)
arr1 = np.random.randint(10, size = (3,5))
arr1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [38]:

np.random.seed(42)
arr1 = np.random.randint(10, size = (3,5))
int(np.argmax(arr1.sum(axis=1)))


1

Extract the diagonal of a matrix
- Don't use np.diag or any of its variants

In [9]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

i_mat = np.eye(3, dtype=int)
diag = mat[i_mat == 1]
diag


array([1, 5, 9])

## 4- Function creation

- Write a function that returns a NumPy array identical to np.linspace(...).

In [19]:
def linespace_custom(start, stop, num=50, endpoint=True):
    pass

In [ ]:
def linespace_custom(start, end, num, endpoint=True):
    if endpoint:
        step = (end - start) / (num - 1)
    else:
        step = (end - start) / num
    return np.array([start + i * step for i in range(num)])

- Write a function that automatically expands dimensions to reach a target ndim.

In [20]:
def expand_to_ndim(arr, ndim):
    pass

In [21]:
def expand_to_ndim(arr, ndim):
    while arr.ndim < ndim:
        arr = arr[np.newaxis, ...]
    return arr




### Problem Description

Given a **2D NumPy array** `arr`, replace each element according to the following rules:

1. Replace with `0` if the element is **less than the mean of its row**.  
2. Replace with `1` if the element is **greater than the mean of its column**.  
3. Replace with `-1` otherwise.  

Rule 1 takes precedence over Rule 2, and Rule 2 takes precedence over Rule 3.

**Constraints:**
- Do **not** use Python loops.
- The output array should have the same shape as the input array.

---

#### Example

```python
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# # Expected Output:
# array([[ 0, -1, -1],
#        [ 0, -1, -1],
#        [ 0,  1,  1]])

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)

def complex_masking(arr):
    pass

In [12]:
import numpy as np

def complex_masking(arr):
    # Step 1: Compute row and column means
    row_means = arr.mean(axis=1, keepdims=True)  # shape (n,1)
    col_means = arr.mean(axis=0, keepdims=True)  # shape (1,m)

    # Step 2: Initialize output with -1
    out = np.full_like(arr, -1)

    # Step 3: Apply conditions independently
    out[arr > col_means] = 1
    out[arr < row_means] = 0

    return out

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
complex_masking(arr)



array([[ 0, -1, -1],
       [ 0, -1, -1],
       [ 0,  1,  1]])

### Problem Description

Given a **1D NumPy array** `arr`, compute the **cumulative sum of only the positive numbers**, keeping zeros or negative numbers unchanged in the resulting array.  

**Constraints:**
- Do **not** use Python loops.
- The output array should have the same shape as the input array.

**hints:**
- You may find `np.cumsum` useful for calculating cumulative sums.
---

#### Example

```python
import numpy as np

arr = np.array([1, -1, 2, 3, -2])
# Expected output: np.array([1, -1, 3, 6, -2])
```


In [ ]:
def conditional_cumsum(arr):
    pass

In [13]:

def conditional_cumsum(arr):
    # Step 1: Create a mask for positive elements
    mask = arr > 0

    # Step 2: Compute cumulative sum for positive elements
    cumsum_positives = np.cumsum(arr * mask)

    # Step 3: Replace positives with their cumulative sum, keep others unchanged
    out = np.where(mask, cumsum_positives, arr)

    return out

arr = np.array([1, -1, 2, 3, -2])
conditional_cumsum(arr)


array([ 1, -1,  3,  6, -2])

### Problem Description
Given a 1D NumPy array `arr` of length `n`, construct an `n × n` matrix where:

- Row `i` contains `arr` shifted **i positions to the right**.
- Empty positions are filled with **zeros**.
- **No Python loops allowed** — must use vectorized NumPy operations.

---

#### Example

**hints:**
- you may find np.where and broadcasting useful.


**Input:**
```python
arr = np.array([1, 2, 3, 4])

# # Expected Output:
# array([
#     [1, 2, 3, 4],
#     [0, 1, 2, 3],
#     [0, 0, 1, 2],
#     [0, 0, 0, 1]
# ])
```


In [ ]:
arr = np.arange(1,5)

def sparse_diagonal_expansion(arr):
    pass

array([1, 2, 3, 4])

In [1]:
import numpy as np

def sparse_diagonal_expansion(arr):
    n = len(arr)
    # For each position (i,j), take arr[j-i] if j>=i, else 0
    indices = np.arange(n) - np.arange(n)[:, None]
    return np.where(indices >= 0, arr[indices], 0)

arr = np.array([1, 2, 3, 4])
sparse_diagonal_expansion(arr)

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [0, 0, 1, 2],
       [0, 0, 0, 1]])